// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzpwjyswrlhzzsunetzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6cHdqeXN3cmxoenpzdW5ldHpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMTIzODMsImV4cCI6MjA2Mjg4ODM4M30.HvEyqXKZIspYoM8YoqF52WmFPuVecxoKZ9sffiA0TjM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);